### ISSUE TITLE
I've stolen `indent/proto.vim` and put them inside `uarun/vim-protobuf`

### ISSUE THREAD

**Issue by timfeirg** [verma/vimrc#1]
Hi, I've copied your `indent/proto.vim` (and modified a little) into https://github.com/uarun/vim-protobuf/pull/5, so that it can have both indent and syntax highlighting, I've mentioned this in the PR but if this isn't OK I should close that PR.

**Comment by verma** [comment]
Its totally fine! :) I haven't really updated my vimrc in a long long time since I primarily use emacs now :/
